### PR TITLE
Set layout to "Other"

### PR DESCRIPTION
**Pull request by locriacyber**
Now it should appear under "Other" in IBus Preferences

### CODE REVIEW

**Comment by salty-horse** [comment]
The current `us` layout is important, since it forces the entry-language for searching emojis to be English. Otherwise, it defaults to the previous layout, which might not be English, and you won't be able to search anything.

So if I have these layouts:
1. English
2. Hebrew
3. UniEmoji

And I cycle from English, through Hebrew, to UniEmoji, I won't be able to type "cake", for example, because the keyboard layout for searching uniemoji would be in Hebrew.

Does this make sense?

Does this change have any effect that's useful to you beyond the cosmetic categorization in the preferences window?

**Comment by locriacyber** [comment]
> And I cycle from English, through Hebrew, to UniEmoji, I won't be able to type "cake", for example, because the keyboard layout for searching uniemoji would be in Hebrew.
Sorry, didn't know that IBus handles keyboard layout as well.

> Does this change have any effect that's useful to you beyond the cosmetic categorization in the preferences window?

No

**Comment by salty-horse** [comment]
So is it to close this? Or do you think it should be an option during installation?

**Comment by locriacyber** [comment]
I think you should add that in readme, that users should find unimoji under "US/English".

I didn't know where to find this IME when I first installed it.

**Comment by salty-horse** [comment]
I see what you mean. I changed it in 75bdd39848a385b6aa00fb09fc5eb56bdcb7df7f and didn't update the README.

**Comment by salty-horse** [comment]
Hmm. I still see it in the "Other" - I don't think it's controlled by the `layout` setting. Maybe it's controlled by `language`.

Where do you see it? Are you using `ibus-setup` like me?
ibus_preferences

**Comment by locriacyber** [comment]
That's really weird. Maybe I was using an old version of unimoji.

**Pull request closed without merging**
