### PR TITLE
Add additional uses of DATADIR and SYSCONFDIR

### PR DESCRIPTION
**Pull request by aske**
Made use of `DATADIR` for icons in `uniemoji.xml.in`.

Also I've moved one xdg fallback path to the separate file `config.py.in`, so it would get replaced by `$SYSCONFDIR`.

### CODE REVIEW

**Comment by salty-horse** [comment]
Thanks!

I've gone ahead and applied your fix to the missing DATADIR in a separate commit.

According to [GNU's guidelines for DESTDIR](https://www.gnu.org/prep/standards/html_node/DESTDIR.html), and helpful folks on freedesktop's IRC channel, it doesn't seem that programs are supposed to be run inside DESTDIR. It's mostly used for testing and as an intermediary step for packaging. I do not think programs should directly reference it.

Agreed?

(I have also made the mistake of adding `DESTDIR` to the `/usr/share` path you changed in uniemoji.xml before realizing it's incorrect 😛)

**Comment by aske** [comment]
Thanks for the info!

Though it doesn't look like uniemoji python files are referencing `DESTDIR`, right?

I've updated PR to skip the change you've commited.
Also what do you think we should do with hardcoded `/etc` in `uniemoji.py`?

**Comment by salty-horse** [comment]
Ugh, you're right. I forgot about `/etc`.

And now there's another problem. We're using the xdg library which isn't aware of whatever SYSCONFDIR you set in the Makefile. I will investigate what's the best course of action.

Regarding the config file:
For now, I want uniemoji.py itself to be usable without any dependencies, and that includes copying and filling in a config file.

How about importing `config` in a `try` block, and appending the config path from there if all goes well.
If it fails, we can append the hard-coded path.

(You don't have to make this change now. I still want to figure out what's the best course of action)

**Comment by salty-horse** [comment]
It's been a while and I couldn't find any answers to this issue.

I'm considering ditching XDG and changing the config dir to `$SYSCONFDIR/uniemoji`.

I'm still for importing `config` in a `try` block, and if that doesn't work, defaulting to `/etc/uniemoji`.

It's a larger change than your patch - do you still want to tackle it, or do you want me to make those changes?

**Comment by aske** [comment]
Thanks for reminding!

No need to remove XDG as it is working fine -- on systems where it's not in the "physical" `/etc/xdg` (like NixOS) variable`$XDG_CONFIG_DIRS`is set the way it works, e.g. we have `/run/current-system/sw/etc/xdg` which contains symlinks to all packages using XDG.
If another non-FHS system (I don't know any others which may use `ibus` or even `xdg`, though) breaks this behavior then they either have a lot to fix inside or pack the program using `pyxdg` differently.

Yeah, wrapping `config` in a `try` block and defaulting to `/etc` seems like the right thing to do.

I've updated PR to reflect these changes.

**Comment by salty-horse** [comment]
Thanks.

So if you have xdg installed, it's OK to use it and ignore `SYSCONFDIR`?

**Comment by aske** [comment]
Yes, `SYSCONFDIR` is used when one doesn't have `pyxdg` for some reason (and as XDG is a default choice I think it's OK to leave it in `xdg/uniemoji`).
Also I think it's OK to leave potential `SYSCONFDIR` and xdg base dir mismatch, because the responsibility to make it operable is of those using `uniemoji`'s make variables in non-conventional ways; it's not likely to happen in practice and someone can (intentionally) devise a lot of ways to do some breakage anyway.

**Comment by salty-horse** [comment]
Pushed as 18eb9044c492fe23ab975e36a1638b661908a832 with a small addition, adding `config.py` to `.gitignore`.

Thanks again for the help!

**Comment by aske** [comment]
Thanks!

**Pull request closed without merging**
